<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="$(find sotuken2017)/urdf/common.xacro"/>
<xacro:include filename="$(find sotuken2017)/urdf/urdf_gazebo.xacro"/>
<xacro:include filename="$(find sotuken2017)/urdf/sensor/khr-forcd_sensor-revolute.xacro"/>

	<property name="ef" value="1.37293"/>
    <property name="vel" value="0.14"/>
	
	<property name="leg_xy" value="0.03"/>
	
	<property name="hips_z" value="0.0039"/>
	<property name="hips_mass" value="0.048"/>
	
	<property name="thigh_z" value="0.026"/>
	<property name="thigh_mass" value="0.068"/>
	
	<property name="knee_z" value="0.088"/>
	<property name="knee_mass" value="0.118"/>
	
	<property name="shin_z" value="0.047"/>
	<property name="shin_mass" value="0.068"/>
	
	<property name="hizakozo_xz" value="0.01"/>
	<property name="hizakozo_mass" value="0.01"/>
	
	<property name="ankle_z" value="0.02"/>
	<property name="ankle_mass" value="0.058"/>
	
	<property name="foot_x" value="0.122"/>
	<property name="foot_y" value="0.078"/>
	<property name="foot_z" value="0.01"/>
	<property name="foot_mass" value="0.03"/>
	
	<property name="foot2_x" value="0.122"/>
	<property name="foot2_y" value="0.078"/>
	<property name="foot2_z" value="0.002"/>
	<property name="foot2_mass" value="0.05"/>

	<xacro:macro name="make_leg" params="parent LRleg ref leg_bool">
 		<joint name="${parent}_to_${LRleg}hips" type="revolute">
  				<parent link="${parent}"/>
  				<child link="${LRleg}hips"/>
 				<origin xyz="0 ${ref * 0.03} -0.0255" rpy="0 0 0"/>
  				<axis xyz="0 0 1"/>
				<dynamics damping="0.5"/>
				<xacro:if value="${leg_bool}">
        			    <limit lower="-${M_PI / 6}" upper="${M_PI / 4}" effort="${ef}" velocity="${vel}"/>
		        </xacro:if>
				<xacro:unless value="${leg_bool}">
						<limit lower="-${M_PI / 4}" upper="${M_PI / 6}" effort="${ef}" velocity="${vel}"/>
				</xacro:unless>
		</joint>

 		<link name="${LRleg}hips">
 				<visual>
   						<origin xyz="0 0 0" rpy="0 0 0"/>
   						<geometry>
    							<box size="${leg_xy} ${leg_xy} ${hips_z}"/>
  						</geometry>
  						<xacro:black/>
  				</visual>

  				<collision>
  						<origin xyz="0 0 0" rpy="0 0 0"/>
   						<geometry>
    							<box size="${leg_xy} ${leg_xy} ${hips_z}"/>
   						</geometry>
  				</collision>

  				<inertial>
   						<origin xyz="0 0 0" rpy="0 0 0"/>
						<xacro:box_inertial m="${hips_mass}" d="${leg_xy}" w="${leg_xy}" h="${hips_z}"/>
				</inertial>
 		</link>

		<joint name="${LRleg}hips_to_${LRleg}thigh" type="revolute">
				<parent link="${LRleg}hips"/>
				<child link="${LRleg}thigh"/>
				<origin xyz="0 0 -0.030" rpy="0 0 0"/>
				<axis xyz="1 0 0"/>
				<dynamics damping="0.5"/>
				<xacro:if value="${leg_bool}">
        			    <limit lower="-${M_PI / 6}" upper="${M_PI / 4}" effort="${ef}" velocity="${vel}"/>
		        </xacro:if>
				<xacro:unless value="${leg_bool}">
						<limit lower="-${M_PI / 4}" upper="${M_PI / 6}" effort="${ef}" velocity="${vel}"/>
				</xacro:unless>
		</joint>

		<link name="${LRleg}thigh">
				<visual>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${thigh_z}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${thigh_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<xacro:box_inertial m="${thigh_mass}" d="${leg_xy}" w="${leg_xy}" h="${thigh_z}"/>
				</inertial>
		</link>

		<joint name="${LRleg}thigh_to_${LRleg}knee" type="revolute">
				<parent link="${LRleg}thigh"/>
				<child link="${LRleg}knee"/>
				<origin xyz="0 0 -0.046" rpy="0 0 0"/>
				<axis xyz="0 1 0"/>
				<dynamics damping="0.5"/>
				<limit lower="-${M_PI * 2 / 3}" upper="${M_PI / 4}" effort="${ef}" velocity="${vel}"/>
		</joint>

		<link name="${LRleg}knee">
				<visual>
						<origin xyz="0 0 -0.034" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${knee_z}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="0 0 -0.034" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${knee_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 0 -0.034" rpy="0 0 0"/>
						<xacro:box_inertial m="${knee_mass}" d="${leg_xy}" w="${leg_xy}" h="${knee_z}"/>
				</inertial>
		</link>

		<joint name="${LRleg}knee_to_${LRleg}hizakozo" type="revolute">
				<parent link="${LRleg}knee"/>
				<child link="${LRleg}hizakozo"/>
				<origin xyz="0 0 -0.078" rpy="0 0 0"/>
				<axis xyz="0 1 0"/>
				<dynamics damping="0.5"/>
				<limit lower="-0.0" upper="${M_PI / 2}" effort="${ef}" velocity="${vel}"/>
		</joint>
		
		<link name="${LRleg}hizakozo">
				<visual>
						<origin xyz="${hizakozo_xz} 0 -0.016" rpy="0 0 0"/>
						<geometry>
								<box size="${hizakozo_xz} ${leg_xy} ${hizakozo_xz}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="${hizakozo_xz} 0 -0.0235" rpy="0 0 0"/>
						<geometry>
								<box size="${hizakozo_xz} ${leg_xy} ${hizakozo_xz}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="${hizakozo_xz} 0 -0.0235" rpy="0 0 0"/>
						<xacro:box_inertial m="${hizakozo_mass}" d="${hizakozo_xz}" w="${leg_xy}" h="${hizakozo_xz}"/>
				</inertial>
		</link>
		
		<joint name="${LRleg}hizakozo_to_${LRleg}shin" type="revolute">
				<parent link="${LRleg}hizakozo"/>
				<child link="${LRleg}shin"/>
				<origin xyz="0 0 -0.032" rpy="0 0 0"/>
				<axis xyz="0 1 0"/>
				<dynamics damping="0.5"/>
				<limit lower="-0.0" upper="${M_PI / 2}" effort="${ef}" velocity="${vel}"/>
		</joint>

		<link name="${LRleg}shin">
				<visual>
						<origin xyz="0 0 -0.0235" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${shin_z}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="0 0 -0.0235" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${shin_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 0 -0.0235" rpy="0 0 0"/>
						<xacro:box_inertial m="${shin_mass}" d="${leg_xy}" w="${leg_xy}" h="${shin_z}"/>
				</inertial>
		</link>

		<joint name="${LRleg}shin_to_${LRleg}ankle" type="revolute">
				<parent link="${LRleg}shin"/>
				<child link="${LRleg}ankle"/>
				<origin xyz="0 0 -0.0319" rpy="0 0 0"/>
				<axis xyz="0 1 0"/>
				<dynamics damping="0.5"/>
				<limit lower="-${M_PI / 2}" upper="${M_PI / 3}" effort="${ef}" velocity="${vel}"/>
		</joint>

		<link name="${LRleg}ankle">
				<visual>
						<origin xyz="0 0 -0.04" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${ankle_z}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="0 0 -0.04" rpy="0 0 0"/>
						<geometry>
								<box size="${leg_xy} ${leg_xy} ${ankle_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 0 -0.04" rpy="0 0 0"/>
						<xacro:box_inertial m="${ankle_mass}" d="${leg_xy}" w="${leg_xy}" h="${ankle_z}"/>
				</inertial>
		</link>

		<joint name="${LRleg}ankle_to_${LRleg}foot" type="revolute">
				<parent link="${LRleg}ankle"/>
				<child link="${LRleg}foot"/>
				<origin xyz="0 0 -0.037" rpy="0 0 0"/>
				<axis xyz="1 0 0"/>
				<dynamics damping="0.5"/>
				<limit lower="-${M_PI / 4}" upper="${M_PI / 4}" effort="${ef}" velocity="${vel}"/>
		</joint>

		<link name="${LRleg}foot">
				<visual>
						<origin xyz="0 ${ref * leg_xy / 2} -0.0312" rpy="0 0 0"/>
						<geometry>
								<box size="${foot_x} ${foot_y} ${foot_z}"/>
						</geometry>
						<xacro:black/>
				</visual>

				<collision>
						<origin xyz="0 ${ref * leg_xy / 2} -0.0312" rpy="0 0 0"/>
						<geometry>
								<box size="${foot_x} ${foot_y} ${foot_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 ${ref * leg_xy / 2} -0.0312" rpy="0 0 0"/>
						<xacro:box_inertial m="${foot_mass}" d="${foot_x}" w="${foot_y}" h="${foot_z}"/>
				</inertial>
		</link>
		
		<!-- set force sensor -->
		<xacro:make_fsensor parent="${LRleg}foot" LR="${LRleg}" num="1">
				<origin xyz="${foot_x / 2 - 0.015}  ${(ref * leg_xy / 2) + (foot_y / 2 - 0.015)} -${0.0315 + foot_z / 2 + box_z / 2}" rpy="0 0 0" />
		</xacro:make_fsensor>
		
		<xacro:make_fsensor parent="${LRleg}foot" LR="${LRleg}" num="2">
				<origin xyz="-${foot_x / 2 -0.015}  ${(ref * leg_xy / 2) + (foot_y / 2 - 0.015)} -${0.0315 + foot_z / 2 + box_z / 2}" rpy="0 0 0" />
		</xacro:make_fsensor>
		
		<xacro:make_fsensor parent="${LRleg}foot" LR="${LRleg}" num="3">
				<origin xyz="${foot_x / 2 -0.015}  ${(ref * leg_xy / 2) - (foot_y / 2 - 0.015)} -${0.0315 + foot_z / 2 + box_z / 2}" rpy="0 0 0" />
		</xacro:make_fsensor>
		
		<xacro:make_fsensor parent="${LRleg}foot" LR="${LRleg}" num="4">
				<origin xyz="-${foot_x / 2 -0.015}  ${(ref * leg_xy / 2) - (foot_y / 2 - 0.015)} -${0.0315 + foot_z / 2 + box_z / 2}" rpy="0 0 0" />
		</xacro:make_fsensor>
		
		<joint name="${LRleg}foot_to_${LRleg}foot2" type="revolute">
				<parent link="${LRleg}foot"/>
				<child link="${LRleg}foot2"/>
				<origin xyz="0 ${ref * leg_xy / 2} -${0.0315 + foot_z / 2 + foot_z / 10 + box_z}" rpy="0 0 0"/>
				<axis xyz="0 0 1"/>
				<limit lower="-0" upper="0" effort="0" velocity="0"/>
		</joint>
		
		<link name="${LRleg}foot2">
				<visual>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<geometry>
								<box size="${foot2_x} ${foot2_y} ${foot2_z}"/>
						</geometry>
						<xacro:gray/>
				</visual>

				<collision>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<geometry>
								<box size="${foot2_x} ${foot2_y} ${foot2_z}"/>
						</geometry>
				</collision>

				<inertial>
						<origin xyz="0 0 0" rpy="0 0 0"/>
						<xacro:box_inertial m="${foot2_mass}" d="${foot2_x}" w="${foot2_y}" h="${foot2_z}"/>
				</inertial>
		</link>
		
		<xacro:gazebo_link_black ref="${LRleg}hips"/>
		<xacro:gazebo_link_black ref="${LRleg}thigh"/>
		<xacro:gazebo_link_black ref="${LRleg}knee"/>
		<xacro:gazebo_link_black ref="${LRleg}hizakozo"/>
		<xacro:gazebo_link_black ref="${LRleg}shin"/>
		<xacro:gazebo_link_black ref="${LRleg}ankle"/>
		<xacro:gazebo_link_black ref="${LRleg}foot"/>
		<xacro:gazebo_link_gray ref="${LRleg}foot2"/>
	</xacro:macro>
</robot>
